# Generated by Django 3.1.6 on 2021-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=20)),
                ('empSalary', models.IntegerField()),
                ('empyAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
